server:
  port: 8001
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: consumer1-feign
  cloud:
    loadbalancer:
      retry:
        enabled: true

ribbon:
 # 同一实例最大重试次数，不包括首次调用
  MaxAutoRetries: 0
 # 重试其他实例的最大重试次数，不包括首次所选的server
  MaxAutoRetriesNextServer: 0
 # 是否所有操作都进行重试
  OkToRetryOnAllOperations: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost1:8801/eureka/,http://localhost2:8802/eureka/